backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
logo_url: https://images.squarespace-cdn.com/content/v1/5b7980cc8ab722614fde37b7/1543591794826-A64J66UBV7QVAQB8ZKQ9/EVOLUTHA-2018-ok.png?format=1500w

collections:
  - name: "totem"
    label: "Totem"
    files:
      - file: "src/pages/index.md"
        label: "Fotografie Slide"
        editor:
          preview: false
        name: "index"
        fields:
          - {label: "Testimmagine", name: "testimmagine", widget: "image"}
